
paths:
  # Path to the git repository root
  base_dir: /path/to/git_repo

  # Path to the experiment directory (can include {experiment_name})
  experiment_dir: /path/to/experiments/{experiment_name}


# parameters to setup the experiment
experiment:
    experiment_name: "Experiment_name"
    extraction_info:
        rois:
            - "full"
        spectrum_types:
            - "1D"
        nose_orientations:
            - "G270_withRC"
            - "nose0_withRC"
            - "G210_withRC"
            - "BSA_90_withRC"
        range_shift_types:
            - "grs"
            - "lrs"
            - "ref"
            - "aircavity"
            - "ABS"
            - "bone"
            - "swelling"
            - "PMMA"
            - "HIPS"
            - "smallaircavity"
        SpotMUs:
            - 0.9
            - 0.8
            - 0.2
            - 0.1
        proton_energies:
            - 139
            - 187
            - 162
            - 159
            - 158
            - 157
        detectors:
            - 12
            - 19
            - 17
            - 15
            - 13
            - 6
            - 8
            - 9
    args:
        data_preprocessing:
            preprocessing_method: "RS_peak"
            RS_peak_shift_method: "single_gaussian" # just important if preprocessing_method = "RS_peak"
            desired_mean_location: 1024
            desired_peak_location: 512
            fit_region:
              - 350
              - 650
            energy_range:
              - 0.7
              - 7.4
            remove_outlier:
              outlier_indices:
              - 0
              - 1
              - 2047
              - 1022
              - 1023
              - 1024
              - 1025
            find_bg_region:
              g_median: 200
              g_gauss: 100
              threshold_factor: 0.05
            find_mean_shift:
              max_iterations: 10000
              tolerance: 0.5
            neighbour_aggregation:
              perform_neighbour_aggregation: "True"
              max_distance: 15.6
              sigma: 7.8
            bg_region: # do not set this, if bg shuld be automatically estimated using fing_bg_region variables
              - 1750
              - 50
            global_time_window:
              - 750 # ca. 3.5ns
              - 1728 # ca. 7.9 ns







